theme: default
layout: default.htm

title: Inspecteur de base de données

JS: /fabweb/js/lib/jquery/jquery-1.2.1.min.js
CSS:/fabweb/styles/databaseinspector.css

searchform:
  template: searchform.html
  JS: 
    - /fabweb/js/lib/jquery/jquery-1.2.1.min.js
    - /fabweb/js/rpc.js

search:
  template: search.html
  max: 1

templates:
  autoinclude:
     fieldset:include/textbox.html
#FIXME: le fieldset ne fonctionne pas dans searchform.html