# Fichier de configuration du module Database

# database : nom symbolique (alias) ou path de la base de données à utiliser.
# il est *fortement* conseillé d'utiliser un alias (définit dans le fichier
# db.yaml de la config).

database: 

# callback : nom de la méthode à appeller comme callback lors des exécutions
# de templates.
# Par défaut, il y a un callback unique (getFiel) qui gère toutes les actions du 
# module, mais vous pouvez indiquer dans le fichier de configuration le nom d'autres 
# callbacks à utiliser en fonction de l'action en cours
callback: getField