# Fichier de configuration du module BisDatabase

# database : nom ou path de la base de données à utiliser.
# vous pouvez soit indiquer un chemin absolu, soit un chemin relatif au
# répertoire /data/db

database: 


# dataset : optionnel, nom de la table à ouvrir au sein de la base database.
# Si vous n'indiquez rien, le nom indiqué dans database est utilisé pour
# déterminer le nom du dataset.
dataset:

# callback : nom de la méthode à appeller comme callback lors des exécutions
# de templates.
# Par défaut, il y a un callback unique (getFiel) qui gère toutes les actions du 
# module, mais vous pouvez indiquer dans le fichier de configuration le nom d'autres 
# callbacks à utiliser en fonction de l'action en cours
callback: getField