# Fichier de configuration du module CartModule

# Nom du panier
name: cart

add:
  template: added.html

remove:
  template: removed.html

clear:
  template: cleared.html

show:
  template: show.html