# Fichier de configuration du module CartModule

# Nom du panier
#name:

sessions:
  use: true

add:
  template: added.html

remove:
  template: removed.html

show:
  template: show.html 