# Fichier de configuration /config/db.yaml
# ----------------------------------------
#
# Ce fichier décrit les bases de données utilisables dans le projet.
# 
# Chaque clé de premier niveau est un nom symbolique donné à la base. C'est ce 
# nom qui sera utilisé dans le projet pour désigner la base.
# 
# type: 
#   type de la base. valeurs possibles : 'bis', 'xapian'.
# 
# path:
#   Requis, le chemin d'accès à la base. Il peut s'agir soit d'un chemin 
#   relatif, soit d'un chemin absolu, soit, dans le cas d'une base xapian de 
#   type 'remote', d'une chaine désignant le serveur et le port à utiliser 
#   (exemple : bdspdev:3333).
#   Si vous indiquez un chemin relatif, celui-ci sera recherché dans le
#   répertoire /data/db de votre application.
#   Dans le cas d'une base bis, le chemin désigne un fichier, dans le cas d'une
#   base xapian classique (ie non remote), il désigne un répertoire.
#   remarque : idem si plus tard on gère du sqlite (path) ou du mysql (host+port)
#
# Pour une base xapian de type 'remote', les paramètres suivants peuvent être
# également indiqués :
#
# timeout: 
#   timeout général de la base lors d'une recherche, d'une modif, etc. 
#   valeur par défaut : 10000 (tout cela est à vérifier).
#
# connect_timeout:
#   timeout lors de la connexion au serveur. Valeur par défaut : 0
#   (tout cela est à vérifier)

ascodocpsy:
    type: bis
    path: ascodocpsy.bed

ascoxapian:
    type: xapian
    path: ascoxapian

