# Config par défaut du framework

# Fuseau horaire de l'application.
# Il peut s'agir du nom d'un fuseau horaire reconnu par la fonction PHP
# date_default_timezone_set (voir http://php.net/timezones pour la liste)
# ou la mention 'default' pour utiliser le fuseau horaire par défaut tel que
# retourné par la fonction PHP date_default_timezone_get
# valeur par défaut : 'default'
timezone: 'default'

# Indique si on utilise des "belles" urls ou non.
# lorsque smarturls est à true, les urls sont de la forme /module/action
# lorsque smarturls est à false, le nom du fichier script php est visible dans 
# l'url : /index.php/module/action
# pour que smarturls puisse fonctionner, le serveur http doit être paramétré 
# pour rediriger toutes les requêtes portant sur un fichier inexistant vers
# le script php utilisé comme point d'entrée unique du site.
# valeur par défaut: false
smarturls: true

defaultroutes: 2
# 0=rien, aucune routes par défaut n'est incluse
# 1=routes minimales qui reconnnaissent juste module/action
# 2=routes étendues qui reconnaissent module/action* (i.e. avec n'importe quel query string)

# Indique le thème à utiliser
theme: default


# Indique le layout à utiliser par défaut
layout: default.htm

debug: false

# paramétrage de la sécurité
security: 
  # Nom du module à utiliser pour la gestion utilisateurs
  handler: NoSecurity


# paramétrage des sessions
sessions:
  # vrai si le site utilise les sessions tout le temps
  use: false
  
  # nom du cookie de session
  id: sid
  
  # durée de vie du cookie de session, en secondes. 0=cookie non stocké
  lifetime: 0


# Paramétrage du gestionnaire de templates
templates:
  # recompile systématiquement tous les templates
  forcecompile:false
  
  # false=ne vérifie pas les dates des fichiers et ne recompile jamais
  checktime:true

# Paramétrage du gestionnaire de configuration
config:
  # false=ne vérifie pas les dates des fichiers et ne recompile jamais
  checktime: true


# Paramétrage du gestionnaire de tâches
taskmanager:
  # port tcp sur lequel le démon va tourner
  port: 86
  
  # timeout (en secondes, un réel) laissé au démon pour répondre à une requête
  timeout: 0.5
  
  # où se trouve l'exécutable php à utiliser en ligne de commande ?
  # Exemple windows :
  php: "c:\php-5.1.4-Win32\php.exe"
  # Exemple linux :
  # php: /usr/local/bin/php
  
  # options éventuelles à passer à l'exécutable php
  phpoptions: "-C -f %s"
  # -n : no php.ini file will be used
  # -C : Do not chdir to the script's directory (implicite dans les versions récentes)
  # -f "xxx" : path du fichier à exécuter

  # comment lancer un programme en tâche de fonds et sans interface ?
#  bgexec: 'start "FAB - Tasks Manager" /B %s'
  bgexec: 'psexec -s -d %s > nul 2>&1' 
#  bgexec: %s