# Fichier de configuration du module DatabaseModule

# database : nom symbolique (alias) ou path de la base de données à utiliser.
# il est *fortement* conseillé d'utiliser un alias (définit dans le fichier
# db.yaml de la config).

database: 

# callback : nom de la méthode à appeller comme callback lors des exécutions
# de templates.
# Par défaut, il n'y a aucun callback de définit.
callback: none
	
# similaire à l'action show mais affiche les données non formatées telles qu'on
# les trouve dans la BDD
rawDBOutput:
  access: admin
  action: show
  callback: none
  template: rawDB.html
  layout: none

#save:
#    template: saved.html
	
# options pour l'action Search 
# peuvent être changées dans le module descendant ou en spécifiant
# _max et _sort dans les paramètres de l'url appellant l'action search
search:
    # ordre de tri par défaut
    sort: "+"
    
    # nombre maximum de réponses par page par défaut
    max: 10

lookup:
  template: ajaxlookup3.html
  layout: none

export:
  list: export.yaml
  template: export.html
  mailtemplate:

  # autoriser la création de fichier zip
  allowzip: true
  # toujours créer un fichier zip, ne pas demander à l'utilisateur
  forcezip: false

  # autoriser l'envoi par mail
  allowmail: true
  # toujours envoyer par mail, ne pas demander à l'utilisateur
  forcemail: false

RSS:
  action: export
  list: rss.yaml
  allowzip: false
  allowmail: false

replaceForm:
  template: replaceForm.html