# Fichier de configuration du module DatabaseModule

# database : nom symbolique (alias) ou path de la base de données à utiliser.
# il est *fortement* conseillé d'utiliser un alias (définit dans le fichier
# db.yaml de la config).

database: 

# callback : nom de la méthode à appeller comme callback lors des exécutions
# de templates.
# Par défaut, il n'y a aucun callback de définit.
callback: none
	
# similaire à l'action show mais affiche les données non formatées telles qu'on
# les trouve dans la BDD
rawDBOutput:
# TODO : accessible qu'en admin normalement
  action: show
  callback: none
  template: rawDB.html
  layout: none

#save:
#    template: saved.html
	
# options pour l'action Search 
# peuvent être changées dans le module descendant ou en spécifiant
# _max et _sort dans les paramètres de l'url appellant l'action search
search:
    sort: "+"      # ordre de tri par défaut
    max: 10        # nombre maximum de réponses par page par défaut
lookup:
  template: ajaxlookup3.html
  layout: none

export:
  list: export.yaml
  template: export.html
#  mailtemplate: email.html

  allowzip: true		# autoriser la création de fichier zip
#  forcezip:true		# toujours créer un fichier zip, ne pas demander à l'utilisateur

  allowmail: true		# autoriser l'envoi par mail
#  forcemail: true		# toujours envoyer par mail, ne pas demander à l'utilisateur
  admin:				# cooordonnées de "qui" envoie le mail (écrase les valeurs de general.yaml)
    name: Site Ascodocpsy
    email: Daniel.Menard@bdsp.tm.fr

RSS:
  action: export
  list: rss.yaml
  allowzip: false
  allowmail: false
